### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by RGunning** [shenlab-sinai/ngsplotdb#1]
Can you explain how to build for set regions?

I have successfully built a genome for mm10 EnsVer 79, but when I install it ngsplotdb.py list shows blank for InstalledFeatures

**Comment by lishen** [comment]
@ny-shao can you look into this? Thx!

**Comment by ny-shao** [comment]
@RGunning Could you provide more details, such as the input and output of the pipeline?

**Comment by RGunning** [comment]
trying to create a mm10 ensembl 79 database

I have set up the files as follows:
animal.json 

```
{
    "ID":1,
    "Assembly": 2,
    "Species": 3,
    "EnsVer": 4,
    "EnsPath": "ftp://ftp.ensembl.org/pub/release-*VERSION*/gtf/*SPECIES*/*SPECIES_NAME*.*GENOME*.*VERSION*.gtf.gz"
}
```

db_list_animal.txt

```
mm10    GRCm38  mus_musculus    79
```

my commands are 

```
genDB.sh db_list_animal.txt animal.json
```

It is running fine and installing into ngsplot.py with no problems. However, when I look at ngsplot.py list i get

```
ID   Assembly Species      EnsVer   NPVer    InstalledFeatures    
mm10 GRCm38   mus_musculus 79.0     3.0        
```

So I cannot create heatmaps around the genebody.

What am I missing?

**Comment by RGunning** [comment]
Ok, Fixed 

My patch of filter_ensembl.py completely fixes this

The problem I experienced was a result of filter_ensembl.py failing to create a biotype.txt file
The GTF file from ensembl has 5 header lines commented with #. filter_enseml.py crashes when it hits the comment lines as it has no process to deal with the lines (the problem actually happens when it tries to perform a string split)

By adding in a line to skip commented lines in the GTF file, filter_ensempl.py runs correctly and creates mm10.ensembl.biotype.txt

I have noticed that I stillget wornings from GTF.pm as it also cannot deal with the comment lines. However, it still completes successfully
